# This is a basic workflow to help you get started with Actions

name: Alternative

# Controls when the workflow will run
on:

  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Alternative
      - name: Auto Github Issue Labeller
        # You may pin to the exact commit or the version.
        # uses: larrylawl/auto-github-issue-labeller-action@3bf15b39ebddda551472f6de4c74083194ee8271
        uses: larrylawl/auto-github-issue-labeller-action@v1.0
        with:
          # Github Repository to label
          REPOSITORY: GitHub_Auto-Labeler # default is larrylawl/Auto-Github-Issue-Labeller
